### PR TITLE
Update deps (semver-major)

### PR DESCRIPTION
**Pull request by sam-github**
Replaces https://github.com/strongloop/modern-syslog/pull/31

https://github.com/nodejs/Release

8, 10, and 12 are still supported

11 is supported until june 1

NOTE this is semver-major:
1. Because it drops CI for old versions
2. Because Buffer.from doesn't exist on out of support node versions (definitely not 0.10, I didn't check when it appears)
3. The latest tap and debug don't suport 0.10 (and I didn't check what their earliest supported version is)

I suggest that it be merged and published as a major update after #35 lands (it currently is based off that branch).

### CODE REVIEW

**Comment by sam-github** [comment]
I guess travis doesn't use the .travis.yml from this branch, but from master?

Failures on node < 8.x above were expected.

**Comment by sam-github** [comment]
@msimerson

**Comment by msimerson** [comment]
By replacing PRs instead of merging them from others you are discouraging contributors from submitting PRs.

**Comment by sam-github** [comment]
I'm sorry you feel that way. I thought your interest was as an employee of IBM, I see now that I was wrong. I'd like you to reconsider how your comment
> I'm over my head and don't know the solution.
from https://github.com/strongloop/modern-syslog/pull/31#discussion_r280617476 would sound to someone like me who has the responsibility of supporting Loopback and IBM across Node.js.

Would you like authorship attribution on d965a1cfbb4ecff6f785958de25209871c806224 and d9959ce0e3c93fbbff1241a0bf63ec4d9a78d805 ? I'm happy to do that (with your permission).

**Comment by msimerson** [comment]
> I'd like you to reconsider how your comment from would sound to someone like me who has the responsibility of supporting Loopback and IBM across Node.js.

I'm happy to consider it.

It doesn't change any of the facts on the ground. I'm a user of the syslog module that came along and invested some time and effort into improving it. [Again](https://github.com/strongloop/modern-syslog/pull/16). I created PRs that could have been merged. Instead of merging you create new commits that do the same things. What's an outside contributor to think? Especially since [no outside PRs have ever been merged](https://github.com/strongloop/modern-syslog/pulls?q=is%3Apr+is%3Aclosed) to this repo. Submitting PRs is contributing and common courtesy is to either request/suggest improvements if needed, and when they are good enough, merge them so the author gets attribution. Submitting PRs is permission *and* an implicit request.

**Comment by sam-github** [comment]
I reassigned authorship to you for the two commits that update travis and package config.

**Pull request merged**
