### PR TITLE
add node 8, 10, and 12 CI testing

### PR DESCRIPTION
**Pull request by msimerson**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by sam-github** [comment]
ok to test

**Comment by msimerson** [comment]
This PR is ready. It drops node 5 CI testing and adds testing for node 8, 10, and 12. It doesn't require 12.x tests to pass, because [they don't](https://travis-ci.org/strongloop/modern-syslog/jobs/527517798). I'll open a new issue for that.

**Comment by sam-github** [comment]
Other than the `fast_finish`  this is replaced by #35. I don't think we need fast_finish, because with #35 and #36 no platforms are allowed to fail. I can reopen this (or add fast_finish to the others) if I misunderstand.

**Pull request closed without merging**
